[workspace]
resolver = "2"
members = [
    "crates/portunus-proto",
    "crates/portunus-bencode",
    "crates/portunus-discovery",
    "crates/portunus-transport",
    "crates/portunus-storage",
    "crates/portunus-engine",
    "portunus-daemon",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Muhammad Mukarram Raza"]
repository = "https://github.com/BSSE23029/portunus"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
async-stream = "0.3"
bytes = "1.6"
criterion = { version = "0.5", default-features = false }
prost = "0.13"
proptest = "1"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
sha1 = "0.10"
thiserror = "2"
tokio = { version = "1.38", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
tonic = "0.12"
tonic-build = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[workspace.lints.rust]
unsafe_code = "forbid"
future_incompatible = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "deny", priority = -1 }
unused_lifetimes = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
todo = "deny"
unimplemented = "deny"
